services:
  guardian:
    image: hydroshieldmkii/guardian:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardian
    ports:
      - "3000:3000"
    volumes:
      - guardian_data:/app/data
    restart: unless-stopped

volumes:
  guardian_data:
    driver: local
