name: Build & Push Multi-Arch (Docker Hub)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/bake-action@v5
        with:
          files: |
            docker-compose.example.yml
          push: true
          set: |
            backend.platform=linux/amd64,linux/arm64
            frontend.platform=linux/amd64,linux/arm64
            backend.tags=docker.io/hydroshieldmkii/guardian-backend:latest
            frontend.tags=docker.io/hydroshieldmkii/guardian-frontend:latest
            backend.cache-from=type=gha,scope=guardian-backend
            backend.cache-to=type=gha,scope=guardian-backend,mode=max
            frontend.cache-from=type=gha,scope=guardian-frontend
            frontend.cache-to=type=gha,scope=guardian-frontend,mode=max
