name: Build & Push to DockerHub

on:
  release:
    types: [published]

concurrency:
  group: dockerhub-publish-${{ github.event.release.tag_name }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

env:
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            docker.io/hydroshieldmkii/guardian-backend:latest
            docker.io/hydroshieldmkii/guardian-backend:${{ env.RELEASE_TAG }}
          cache-from: type=gha,scope=guardian-backend
          cache-to: type=gha,scope=guardian-backend,mode=max
          outputs: type=image,name=docker.io/hydroshieldmkii/guardian-backend,push=false

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            docker.io/hydroshieldmkii/guardian-frontend:latest
            docker.io/hydroshieldmkii/guardian-frontend:${{ env.RELEASE_TAG }}
          cache-from: type=gha,scope=guardian-frontend
          cache-to: type=gha,scope=guardian-frontend,mode=max
          outputs: type=image,name=docker.io/hydroshieldmkii/guardian-frontend,push=false

  push-backend:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push Backend (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/hydroshieldmkii/guardian-backend:latest
            docker.io/hydroshieldmkii/guardian-backend:${{ env.RELEASE_TAG }}
          cache-from: type=gha,scope=guardian-backend

  push-frontend:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push Frontend (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/hydroshieldmkii/guardian-frontend:latest
            docker.io/hydroshieldmkii/guardian-frontend:${{ env.RELEASE_TAG }}
          cache-from: type=gha,scope=guardian-frontend

  publish-confirmation:
    runs-on: ubuntu-latest
    needs: [push-backend, push-frontend]
    steps:
      - run: echo "✅ Release ${{ env.RELEASE_TAG }} images built and published."
