name: Build & Push Multi-Arch (Docker Hub)

on:
  push:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/hydroshieldmkii/guardian-backend:latest
          cache-from: type=gha,scope=guardian-backend
          cache-to: type=gha,scope=guardian-backend,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/hydroshieldmkii/guardian-frontend:latest
          cache-from: type=gha,scope=guardian-frontend
          cache-to: type=gha,scope=guardian-frontend,mode=max

  publish-confirmation:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - run: echo "Both backend and frontend images built and published successfully."
